### PR TITLE
fix: null pointer exception in ClusterRenderer when continuously updating cluster item values

### LINKED ISSUE #622: Null Pointer Exception in ClusterRenderer When Continuously Updating Cluster Item Values
#### Environment details

1. Android API 30
2. kotlin 1.8.10
3. maps compose 5.0.4
4. agp 8.4
5. compose 1.9.1

#### Steps to Reproduce

1. Start with a mutable state list that is provided to the clustering composable.
2. Continuously update the list within a `while` loop.
3. Observe that the cluster changes its position as the list updates.
4. Zoom in on the cluster until individual items are visible.
5. Notice that a null pointer exception occurs during this process.

#### Related Codes

```
val list = remember {
          mutableStateOf(
              mutableListOf(Vehicle(
                  lat = 0.5,
                  lng = 0.5
              ),Vehicle(
                  lat = 0.8,
                  lng = 0.8
              ),Vehicle(
                  lat = 1.5,
                  lng = 1.5
              ),Vehicle(
                  lat = 0.6,
                  lng = 0.6
              ),Vehicle(
                  lat = 0.7,
                  lng = 0.5
              ),Vehicle(
                  lat = 0.10,
                  lng = 0.17
              ),Vehicle(
                  lat = 0.61,
                  lng = 0.91
              ),Vehicle(
                  lat = 0.61,
                  lng = 0.91
              ),Vehicle(
                  lat = 0.63,
                  lng = 0.91
              ),Vehicle(
                  lat = 0.656,
                  lng = 0.91
              ),Vehicle(
                  lat = 0.6116,
                  lng = 0.94
              ),Vehicle(
                  lat = 0.61,
                  lng = 0.94
              ),Vehicle(
                  lat = 0.621,
                  lng = 0.912
              ),Vehicle(
                  lat = 0.62,
                  lng = 0.91
              ),Vehicle(
                  lat = 0.61,
                  lng = 0.39
              ))
          )
      }

```
```
Clustering(items = list,
                    onClusterClick = {
                        scope.launch {
                            cameraPositionState.animate(
                                CameraUpdateFactory.newLatLngZoom(it.position,20f)
                            )
                        }
                       false
                   }, clusterItemContent = {
                        InfoWindow(asset = it)
                   })
                   )
```

```
 LaunchedEffect(key1 = Unit) {
        while (true){
            list.value.first().lat = list.value.first().lat?.plus(0.1)
            delay(100)
        }
    }
```

#### Stack trace
```
java.lang.NullPointerException: null cannot be cast to non-null type android.view.ViewGroup
    at com.google.maps.android.compose.clustering.ComposeUiClusterRenderer.renderViewToBitmapDescriptor(ClusterRenderer.kt:175)
    at com.google.maps.android.compose.clustering.ComposeUiClusterRenderer.onBeforeClusterItemRendered(ClusterRenderer.kt:167)
    at com.google.maps.android.clustering.view.DefaultClusterRenderer$CreateMarkerTask.perform(DefaultClusterRenderer.java:1060)
    at com.google.maps.android.clustering.view.DefaultClusterRenderer$CreateMarkerTask.access$1900(DefaultClusterRenderer.java:1027)
    at com.google.maps.android.clustering.view.DefaultClusterRenderer$MarkerModifier.performNextTask(DefaultClusterRenderer.java:740)
    at com.google.maps.android.clustering.view.DefaultClusterRenderer$MarkerModifier.handleMessage(DefaultClusterRenderer.java:710)
    at android.os.Handler.dispatchMessage(Handler.java:107)
    at android.os.Looper.loop(Looper.java:225)
    at android.app.ActivityThread.main(ActivityThread.java:7563)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:994)

```

### PR DESCRIPTION
**Pull request by mohammad-firmansyah**
Thank you for opening a Pull Request!

---

Before submitting your PR, there are a few things you can do to make sure it goes smoothly:
- [x] Make sure to open a GitHub issue as a bug/feature request before writing your code!  That way we can discuss the change, evaluate designs, and agree on the general idea
- [x] Ensure the tests and linter pass
- [x] Code coverage does not decrease (if any source code was changed)
- [x] Appropriate docs were updated (if necessary)

Fixes #622  🦕

### CODE REVIEW

File: maps-compose-utils/src/main/java/com/google/maps/android/compose/clustering/ClusterRenderer.kt [hunk 1]
```diff
@@ -168,26 +168,35 @@ internal class ComposeUiClusterRenderer<T : ClusterItem>(
         }
     }
 
-    private fun renderViewToBitmapDescriptor(view: AbstractComposeView): BitmapDescriptor {
+    private fun renderViewToBitmapDescriptor(view: AbstractComposeView?): BitmapDescriptor {
```
Comment (Goooler) [inline maps-compose-utils/src/main/java/com/google/maps/android/compose/clustering/ClusterRenderer.kt:171]:
```suggestion
    private fun renderViewToBitmapDescriptor(view: AbstractComposeView): BitmapDescriptor {
```

File: maps-compose-utils/src/main/java/com/google/maps/android/compose/clustering/ClusterRenderer.kt [hunk 2]
```diff
@@ -168,26 +168,35 @@ internal class ComposeUiClusterRenderer<T : ClusterItem>(
...
+            }
+            return BitmapDescriptorFactory.fromBitmap(bitmap)
+        } else {
+            val bitmap = Bitmap.createBitmap(
+                20,
+                20,
+                Bitmap.Config.ARGB_8888
+            )
+            return BitmapDescriptorFactory.fromBitmap(bitmap)
         }
```
Comment (Goooler) [inline maps-compose-utils/src/main/java/com/google/maps/android/compose/clustering/ClusterRenderer.kt:199]:
```suggestion
        view.draw(fakeCanvas)
        val viewParent =
            view.parent as? ViewGroup ?: return Bitmap.createBitmap(20, 20, Bitmap.Config.ARGB_8888)
                .let(BitmapDescriptorFactory::fromBitmap)
        view.measure(
            View.MeasureSpec.makeMeasureSpec(viewParent.width, View.MeasureSpec.AT_MOST),
            View.MeasureSpec.makeMeasureSpec(viewParent.height, View.MeasureSpec.AT_MOST),
        )
        view.layout(0, 0, view.measuredWidth, view.measuredHeight)
        val bitmap = Bitmap.createBitmap(
            view.measuredWidth.takeIf { it > 0 } ?: 1,
            view.measuredHeight.takeIf { it > 0 } ?: 1,
            Bitmap.Config.ARGB_8888
        )
        bitmap.applyCanvas {
            view.draw(this)
        }

        return BitmapDescriptorFactory.fromBitmap(bitmap)
```

File: maps-compose-utils/src/main/java/com/google/maps/android/compose/clustering/ClusterRenderer.kt (hunk 1 above)
Comment (Goooler) [reply maps-compose-utils/src/main/java/com/google/maps/android/compose/clustering/ClusterRenderer.kt:171]: From your stacktrace, the NPE doesn't happen from this view but it's parent, I believe we have no need to make it nullable.

Comment (mohammad-firmansyah) [reply maps-compose-utils/src/main/java/com/google/maps/android/compose/clustering/ClusterRenderer.kt:171]: that's true i just realized that thanks

**Review by Goooler — APPROVED** [review]
LGTM. I'm not the maintainer, though :)

**Review by dkhawk — APPROVED** [review]
