### PR TITLE
fix: Ensure CameraPositionState map reference clears when GoogleMap l…

### LINKED ISSUE #106: "CameraPositionState may only be associated with one GoogleMap at a time" when used with Accompanist's HorizontalPager
Coming across a crash when trying to embed a `GoogleMap` inside a `HorizontalPager` when the `CameraPositionState` is hoisted outside of the pager

#### Environment details
* Android Studio `Bumblebee 2021.1.1 Patch 3`
* Kotlin `1.6.20`
* Compose `1.2.0-alpha08`
* Accompanist `0.24.7-alpha`
* maps-compose `2.1.0`

#### Steps to reproduce

* I've created a demo of the bug here: https://github.com/nathanjde/pagerbug-maps-compose (based off the android-maps-compose demo repo and a [single additional commit](https://github.com/nathanjde/pagerbug-maps-compose/commit/65e1881f80333333a673b762775bfe5023af5dfc)
* Bug can be reproduced when swiping to the last pager page and back again to the first, or by clicking on any "Details" pager tab and back to the map again

#### Stack trace
```
java.lang.IllegalStateException: CameraPositionState may only be associated with one GoogleMap at a time
    at com.google.maps.android.compose.CameraPositionState.setMap$maps_compose_release(CameraPositionState.kt:144)
    at com.google.maps.android.compose.MapPropertiesNode.<init>(MapUpdater.kt:40)
    at com.google.maps.android.compose.MapUpdaterKt$MapUpdater$1.invoke(MapUpdater.kt:121)
    at com.google.maps.android.compose.MapUpdaterKt$MapUpdater$1.invoke(MapUpdater.kt:119)
    at com.google.maps.android.compose.MapUpdaterKt$MapUpdater$$inlined$ComposeNode$1.invoke(Composables.kt:225)
...
```

### PR DESCRIPTION
**Pull request by arriolac**
Fixes the issue where the `CameraPositionState` maintains a reference to a `GoogleMap` when it is hoisted. The previous implementation did not appropriately clean up after the `GoogleMap` composable leaves the composition.

TODO:
- [x] Write unit test

Fixes #106 🦕

### CODE REVIEW

File: maps-compose/src/main/java/com/google/maps/android/compose/CameraPositionState.kt [hunk 1]
```diff
@@ -104,7 +104,7 @@ class CameraPositionState(
 
     // The map currently associated with this CameraPositionState.
     // Guarded by `lock`.
-    private var map: GoogleMap? = null
+    var map: GoogleMap? = null
```
Comment (NitroG42) [inline maps-compose/src/main/java/com/google/maps/android/compose/CameraPositionState.kt:107]: Is there any reason to expose the GoogleMap instance there ?

File: app/src/main/java/com/google/maps/android/compose/MapSampleActivity.kt [hunk 2]
```diff
@@ -191,6 +196,11 @@ fun GoogleMapView(
         ) {
             Text(text = "RESET MAP", style = MaterialTheme.typography.body1)
         }
+        Button(
```
Comment (barbeau) [inline app/src/main/java/com/google/maps/android/compose/MapSampleActivity.kt:199]: Not sure if this is intentional, but this button is a different style than the others due to Button colors and Text style. It's also missing the 4.dp of padding:

image

File: maps-compose/src/main/java/com/google/maps/android/compose/CameraPositionState.kt (hunk 1 above)
Comment (barbeau) [reply maps-compose/src/main/java/com/google/maps/android/compose/CameraPositionState.kt:107]: Same - was this intentional?

**Review by barbeau — COMMENTED** [review]
Thanks for this @arriolac! Two comments in-line.

File: app/src/main/java/com/google/maps/android/compose/MapSampleActivity.kt (hunk 2 above)
Comment (arriolac) [reply app/src/main/java/com/google/maps/android/compose/MapSampleActivity.kt:199]: Will also align this in the same Row as "RESET MAP"

**Review by barbeau — APPROVED** [review]
LGTM!

In a future PR we will need to update the app `build.gradle` to depend on the new release with this fix otherwise users will get a crash when tapping the "Toggle Map" button.
